### ISSUE TITLE
1.1.3 堆栈 我们之前谈论的最早的计算机只允许顺序执行程序 语句顺序

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#10]
> 我们之前谈论的最早的计算机只允许顺序执行程序，从打孔卡或胶片中依次读取每个指令

这里的 “从打孔卡” 的主语需要重复一次上下文才能理解是 最早的计算机 是否可以修改为

我们之前谈论的最早的计算机只能从打孔卡或胶片中依次读取每个指令，只允许顺序执行程序

通过 只能 和 只允许 可以联系上下两个语句

**Comment by weiminye** [comment]
Good point. Thanks point out. added into '第1章.md'
