### ISSUE TITLE
1.1.3 堆栈 需要调用程序不同部分的可能性是需要可寻址的

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#11]
“需要调用程序不同部分的可能性是需要可寻址的” 这句话没读通

想要调用程序不同部分的前提是程序是支持可寻址的

需要让程序支持可寻址的才能让调用程序不同部分成为可能

让调用程序不同部分成为可能需要支持可寻址的 xx (可寻址的 主语 如内存)

**Comment by weiminye** [comment]
直译的确难以读懂，所以只能改为意译了。

**Comment by weiminye** [comment]
改为“要能调用程序不同部分的前提是程序是支持可寻址的”
