### ISSUE TITLE
1.1.3 堆栈 编写可以从整个程序的不同角度 转折太快

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#12]
我们之前谈论的最早的计算机只允许顺序执行程序，从打孔卡或胶片中依次读取每个指令。 但是，编写可以从整个程序的不同角度重用的程序某些部分(子例程)的想法显然很诱人

这个 “但是” 的转折太快

为什么顺序执行会存在 但是编写 xx 也很诱人

是否加上一句话描述顺序存在的问题

顺序执行意味着不能很好的执行某些可以重用的程序，但是编写可以从整个程序的不同角度重用的程序某些部分(子例程)的想法显然很诱人

**Comment by weiminye** [comment]
added
