### ISSUE TITLE
1.1.3 堆栈 可能是图灵在他的1940年代初编写的描述自动计算机引擎

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#13]
可能是图灵在他的1940年代初编写的描述自动计算机引擎(ACE)的报告中提到的

加上 “他的” 读起来不顺

可能是图灵在1940年代初编写的描述自动计算机引擎(ACE)的报告中提到的

**Comment by lindexi** [comment]
我们今天在计算机架构中所了解的堆栈概念的第一次被提及，可能是图灵在他的1940年代初编写的描述自动计算机引擎(ACE)的报告中提到的

是否可以更改为 在世界上的首次被提及

**Comment by weiminye** [comment]
add into 第1章.md
