### ISSUE TITLE
1.1.6堆  当给定的内存块返回内存池以备将来使用时 句子读不通

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#14]
当给定的内存块返回内存池以备将来使用时，即分配操作的反向操作，称之为释放

这里 “当” 是否应该改为 “将”

将给定的内存块返回内存池以备将来使用时

**Comment by weiminye** [comment]
原文为when，不过改为”将“也能和原文对应，故采纳之。added into 第1章.md
