### ISSUE TITLE
1.1.6堆 堆如何精确地分配具有给定大小的空间是一个实现细节 句子读不通

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#15]
堆如何精确地分配具有给定大小的空间是一个实现细节。有许多“分配器”，我们将很快了解到其中的一些。

`堆如何精确地分配具有给定大小的空间` 主语 是 `一个实现细节` 读起来有点诡异

`有许多“分配器”` 这里缺少用途，推荐如下

- 有许多“分配器” 用于实现它，我们将很快了解到其中的一些
- 有许多“分配器” 用于实现这个细节，我们将很快了解到其中的一些

**Comment by weiminye** [comment]
堆<font color=red>是</font>如何精确地分配具有给定大小的空间<font color=red>这点</font>是一个实现细节。有许多“分配器” <font color=red>用于实现这个细节</font>，我们将很快了解到其中的一些。

**Comment by weiminye** [comment]
added
