### ISSUE TITLE
1.1.6堆 没有足够的可用空间给予给定对象，尽管总的来说堆上有足够的可用空间 缺乏注释

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#16]
没有足够的可用空间给予给定对象，尽管总的来说堆上有足够的可用空间。 这种情况称为堆碎片

为什么这样称为 “堆碎片” 是否可以加上一句原因

- 没有足够的可用空间给予给定对象，尽管总的来说堆上有足够的可用空间，因为可用空间都不连续。 这种情况称为堆碎片
- 没有足够的可用连续空间给予给定对象，尽管总的来说堆上有足够的可用空间，因为可用空间都不连续。 这种情况称为堆碎片

**Comment by weiminye** [comment]
我改为了”没有足够的可用空间给予给定对象，尽管总的来说堆上有足够的可用空间，但是这些可用空间是不连续的。 这种情况称为堆碎片“

add into 第1章.md
