### ISSUE TITLE
1.1.6堆 的堆栈应该是栈才对

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#17]
表1-1 堆栈和堆特性的比较

这些对 堆栈和堆 的描述，的 堆栈 应该是 栈 才对

**Comment by weiminye** [comment]
@lindexi 根据

- https://www.wikiwand.com/zh-hans/%E5%A0%86%E6%A0%88 
- https://baike.baidu.com/item/%E5%A0%86%E6%A0%88 
- https://baike.baidu.com/item/%E6%A0%88/12808149

里的定义，“堆栈”和“栈“是同义词。

我打算这么处理，写在<.NET内存管理宝典>阅读指南的blog里面

**Comment by weiminye** [comment]
已经写进https://www.cnblogs.com/adalovelacer/p/13436610.html 里面了
