### ISSUE TITLE
1.2手动内存管理  在这个过程中 缺少前提

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#18]
我来自欧洲，我们只是习惯于手动变档汽车。在这个过程中, 我们必须考虑现在是不是变档的好时机，还是应该等几秒钟，直到发动机转速足够高才变档。

没有说明 在这个过程中 说的是哪个过程。尽管老司机是知道在是否变档的过程

**Comment by weiminye** [comment]
改为”驾驶“过程。add into 第1章.md
