### ISSUE TITLE
1.2手动内存管理 这种语言与其他编程语言的关联是巨大的

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#19]
原文： 这种语言与其他编程语言的关联是巨大的，无法想象

问题：这里的“无法想象”缺乏上下文，应该表示的是无法想象的巨大关联

参考：

 - 这种语言与其他编程语言有无法想象的巨大的关联

**Comment by weiminye** [comment]
add into 第1章.md
