### ISSUE TITLE
1.2手动内存管理 在上面这样一个简单的示例中，当然真的很难忘记调用free函数

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#20]
原文：在上面这样一个简单的示例中，当然真的很难忘记调用free函数

问题：没有说明 free 函数是什么

参考：在上面这样一个简单的示例中，当然真的很难忘记调用 free（释放内存）函数

**Comment by weiminye** [comment]
add into 第1章.md
