### ISSUE TITLE
1.3.1分配器、Mutator和回收器 通常会讨论回收器对mutator的影响

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#21]
原文：在考虑各种垃圾回收设计时，通常会讨论回收器对mutator的影响，反之亦然

问题：mutator应该是大写的

参考：在考虑各种垃圾回收设计时，通常会讨论回收器对Mutator的影响，反之亦然

**Comment by weiminye** [comment]
add into 第1章.md
