### ISSUE TITLE
3.回收器(Collector) 因此回收器通常被称为垃圾回收器或简称为GC

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#22]
原文：显然，因此回收器通常被称为垃圾回收器或简称为GC。

问题：缺乏简称的描述，同时 “显然，因此” 放一起太过强烈

参考：显然，这就是回收器通常被称为垃圾回收器（Garbage Collection）或简称为GC的原因

**Comment by weiminye** [comment]
added into 第1章.md
