### ISSUE TITLE
1.5跟踪回收器(Tracking Collector )  停止标记阶段所需的世界

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#23]
原文： 停止标记阶段所需的世界 - 但仅限于非并行形式

问题：错别字 世界 应该是 时间

参考：停止标记阶段所需的时间 - 但仅限于非并行形式

**Comment by weiminye** [comment]
@lindexi 
原文是“Stop the world needed for Mark phase - but only in a non-concurrent flavor.” 所以这里不是错别字.

我打算写在blog<.NET内存管理宝典>阅读指南里面

**Comment by weiminye** [comment]
已经添加进blog:  《.NET内存管理宝典 》（Pro .NET Memory Management） 阅读指南 - 第1章  https://www.cnblogs.com/adalovelacer/p/13436610.html

**Comment by lindexi** [comment]
@weiminye 这里的世界好像直接翻译不是很好，哈哈，我开始以为是错别字。是否作为 工作空间 之类？
