### ISSUE TITLE
第2章 底层内存管理 所以这些东西都会影响到.NET的运行机制和代码编写方式

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#24]
原文：硬件、操作系统、编译器，所以这些东西都会影响到.NET的运行机制和代码编写方式

问题：错别字 所以 应该是 所有

参考：硬件、操作系统、编译器，所有这些东西都会影响到.NET的运行机制和代码编写方式

**Comment by weiminye** [comment]
已经添加到**第2章.md**里的"**必须要改的 - 错别字**"
