### ISSUE TITLE
我没想到在编写本书的过程中我们需要牺牲这么多何她在一起的时间

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#26]
原文： 我没想到在编写本书的过程中我们需要牺牲这么多何她在一起的时间

问题：错别字 多何她->多和她

参考：我没想到在编写本书的过程中我们需要牺牲这么多和她在一起的时间

**Comment by weiminye** [comment]
已经添加到**第1章之前.md**的“**必须要改的 - 错别字**”一栏里
