### ISSUE TITLE
【知识点】2.2.6Windows内存布局 segment heap：用于Universal Windows Platform程序 

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#27]
原文： segment heap：用于Universal Windows Platform程序，它提供了更精密的allocator(其中包括与上面类似的low-fragmentation allocator)

问题：现在已支持 win32 程序了，请看 https://blogs.windows.com/msedgedev/2020/06/17/improving-memory-usage/  segment heap memory improvements now available for Win32 applications

**Comment by weiminye** [comment]
已经添加到第2章.md里的建议加译者注 - 额外知识点，并且还加进了 https://www.cnblogs.com/adalovelacer/p/pro-dot-net-memory-management-guide-2.html 。 另外你好像有两个blog，我不知道要在“致谢”里加你哪一个

**Comment by lindexi** [comment]
@weiminye 佛系哈
