### ISSUE TITLE
【语句】2.2.6Windows内存布局 我们将在第4章基于这个理由提高stack大小的上限

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#30]
原文：我们将在第4章基于这个理由提高stack大小的上限。

问题：上文说到 “但如果我们出于某种理由，确实需要在stack上存储大量数据” 但是后文说到 “基于这个理由” 此时的逻辑有点诡异，也就是没有明确出理由是什么

参考：我们将在第4章告诉大家如何提高stack大小的上限

**Comment by weiminye** [comment]
added into  第2章.md
