### ISSUE TITLE
【知识】2.3NUMA和CPU组 这就是non-uniform memory architecture(NUMA)大显身手的舞台

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#32]
原文：这就是non-uniform memory architecture(NUMA)大显身手的舞台

问题：缺少中文描述

参考：这就是non-uniform memory architecture(NUMA，非统一内存访问)大显身手的舞台

**Comment by weiminye** [comment]
added into 第2章.md 里 '建议补充语句的 - 额外知识点'
