### ISSUE TITLE
【知识】2.3NUMA和CPU组 理论上，可以通过设置runtime配置段中的GCNumaAware配置项禁用NUMA感知

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#33]
原文：理论上，可以通过设置runtime配置段中的GCNumaAware配置项禁用NUMA感知，但目前这个配置项尚未公开。

问题：好像是支持了，在 [Making CPU configuration better for GC on machines with > 64 CPUs](https://devblogs.microsoft.com/dotnet/making-cpu-configuration-better-for-gc-on-machines-with-64-cpus/ ) 有说道，使用 GCNumaAware 可以设置

**Comment by weiminye** [comment]
added into 第2章.md
