### ISSUE TITLE
【错别字】第 3 章 内存测量 数十种要以正确顺序来使用的魔术命令的知识将值得我们进行大量的研究

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#35]
原文：数十种要以正确顺序来使用的魔术命令的知识将值得我们进行大量的研究

问题：应该是魔法命令，而不是魔术命令

参考：数十种要以正确顺序来使用的魔法命令的知识将值得我们进行大量的研究

**Comment by weiminye** [comment]
加在第3章.md的 建议修改的 - 用词习惯里面
