### ISSUE TITLE
【语法】 第 3 章 内存测量 因为我们通常不知道哪些是“可能”或“应该”的

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#37]
原文：因为我们通常不知道哪些是“可能”或“应该”的。

问题：缺少宾语，如不知道代码，或不知道性能点

参考：因为我们通常不知道哪些代码是“可能”或“应该”的

**Comment by weiminye** [comment]
Processed! Add into '第3章.md'
