### ISSUE TITLE
修正表 markdown 文档格式不对

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#38]
![](https://user-images.githubusercontent.com/16054566/90704297-aea80080-e2c2-11ea-8d70-5feefebb96a7.png)

这里的分段应该是添加空行，否则将会两行合并为一段

```diff
- 出处：“2.1 硬件”一节再往前两个自然段 
- 原文：对于典型的32位程序，默认值时1MB
+ 出处：“2.1 硬件”一节再往前两个自然段 
+ 
+ 原文：对于典型的32位程序，默认值时1MB
```

**Comment by weiminye** [comment]
已纠正，看来Github对markdown的支持与VS Code的Markdown插件效果不一样，比如字体颜色都没有显示出来
