### ISSUE TITLE
【语法】3.1.3调用树 每个函数还附有一些测量，很可能是总执行时间

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#39]
原文：每个函数还附有一些测量，很可能是总执行时间

问题：原文“很可能是总执行时间”缺少主语，指的是 每个函数很可能是总执行时间 还是 测量很可能是总执行时间 

参考：每个函数还附有一些测量，这些测量很可能是总执行时间

**Comment by weiminye** [comment]
经过讨论，最终决定此处不做修改。
