### ISSUE TITLE
【语法】 3.1.6延迟与吞吐量 它们有时也会被误解和错误解释

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#41]
原文：它们有时也会被误解和错误解释

问题：应该不会是同时存在误解和错误解释

参考：它们有时也会被误解~~和~~或错误解释

**Comment by weiminye** [comment]
added into 第3章.md 建议修改的 - 为了方便读者理解或让意思更加明确
