### ISSUE TITLE
【标点】 3.1.6延迟与吞吐量 b)在缩短延迟的情况下

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#42]
原文：(a)在某些基本延迟下，我们每X秒可以处理5个请求；b)在缩短延迟的情况下，我们每X秒可以处理7个请求，(c)通过加倍并行化，我们使吞吐量加倍为每X秒10个请求，而无需改变延迟

问题： 这里的 b 缺少括号

参考：(b)在缩短延迟的情况下

**Comment by weiminye** [comment]
出版社最新的排版已经纠正了这个问题
