### ISSUE TITLE
【语法】 3.2Windows环境 我们将把大部分时间都花在它们身上，只是因为它们将在本书后面经常被使用

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#46]
原文：我们将把大部分时间都花在它们身上，只是因为它们将在本书后面经常被使用

问题：只是因为的只是看起来是多余的

参考：我们将把大部分时间都花在它们身上，因为它们将在本书后面经常被使用

**Comment by weiminye** [comment]
经过讨论，最终决定此处不做修改。
