### ISSUE TITLE
【错别字】 3.2.3性能计数器 许多监控工具都是使用性能计数器做为基础的

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#47]
原文：许多监控工具都是使用性能计数器做为基础的

问题：应该是作为

参考：许多监控工具都是使用性能计数器~~做为~~作为基础的

**Comment by weiminye** [comment]
added into 第3章.md 里的 建议修改的 - 有可能是错别字
