### ISSUE TITLE
【语法】 3.2.5Windows性能工具包  但是，从Windows 8开始，Windows性能工具包引入了两个新工具

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#48]
原文：由于xperf是一种非常灵活的工具，因此仍然偶尔用于从命令行管理ETW会话。但是，从Windows 8开始，Windows性能工具包引入了两个新工具

问题：这里的 “但是” 代表转折，但实际上没有真的存在转折的内容。但是，从xx开始，工具包引入了xx工具，可以替换原有的工具。这样的但是才是转折

参考：由于xperf是一种非常灵活的工具，因此仍然偶尔用于从命令行管理ETW会话。但是，从Windows 8开始，Windows性能工具包引入了两个新的更常用的工具

**Comment by weiminye** [comment]
经过讨论，最终决定此处不做修改
