### ISSUE TITLE
1.1.2寄存器机 我们计算机使用的所有...

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#5]
> 我们计算机使用的所有Intel和 AMD CPU 都是以这种方式运行的

应该添加 "的" 在 AMD CPU 中间

我们计算机使用的所有Intel和 AMD 的 CPU 都是以这种方式运行的

**Comment by weiminye** [comment]
add into 第1章.md
