### ISSUE TITLE
【语法】 2..Windows Performance Analyzer 该接口是以一种非常通用的方式设计的

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#50]
原文： 与该工具的第一次接触可能会让人有些不知所措。该接口是以一种非常通用的方式设计的

问题： 上文没有说到 接口 所以这里的 该接口 没有指定。这里应该是 该工具的界面

参考：与该工具的第一次接触可能会让人有些不知所措。该工具的界面是以一种非常通用的方式设计的

**Comment by weiminye** [comment]
同意！ good catch! thank you . added into 第3章.md
