### ISSUE TITLE
【语法】 2..Windows Performance Analyzer 其意味着将进行10个并发呼叫

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#51]
原文： 其意味着将进行10个并发呼叫，它们之间的间隔为100毫秒，总共将进行100,000个呼叫

问题： 用 意味着 这个词不太准，因为只有做什么事情，意味着什么

参考： 使用这个工具意味着将进行10个并发呼叫，它们之间的间隔为100毫秒，总共将进行100,000个呼叫

**Comment by lindexi** [comment]
参考： 运行上面命令行意味着将进行10个并发呼叫，它们之间的间隔为100毫秒，总共将进行100,000个呼叫

**Comment by lindexi** [comment]
另外，考虑在中文，这里的 sb.exe 好像不太好

sb 是 傻逼 的缩写

**Comment by weiminye** [comment]
> 原文： 其意味着将进行10个并发呼叫，它们之间的间隔为100毫秒，总共将进行100,000个呼叫
> 
> 问题： 用 意味着 这个词不太准，因为只有做什么事情，意味着什么
> 
> 参考： 使用这个工具意味着将进行10个并发呼叫，它们之间的间隔为100毫秒，总共将进行100,000个呼叫

不是***使用这个工具***而是***上面这段代码***

并且经过讨论，此处不做修改
