### ISSUE TITLE
【名词】Full GC，是全面GC还是完全GC更好？

### ISSUE THREAD

**Issue by sPhinX-LHJ** [weiminye/pro-dotnet-memory-mgr-translation-review#52]
我个人觉得完全GC感觉好些

**Comment by weiminye** [comment]
以“完全GC”为关键字在google的相关搜索结果比"全面GC"为关键字的相关搜索结果多。因此采纳“完全GC”。added into 第3章.md，第7章.md，第11章.md，第15章.md。 但是最终决定权在于出版社的编辑

**Comment by weiminye** [comment]
最终决定权在于出版社的编辑
