### ISSUE TITLE
【错别字】 3.3.2 Perfcollect 你需要导出两个环境变量

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#56]
原文：然后，启动跟一个踪会话，你需要导出两个环境变量(第一个环境变量允许生成解码映射，，用于从记录的跟踪中解码符号

问题：多了一个逗号，少了跟字

参考：然后，启动跟**踪**一个 ~~踪~~ 会话，你需要导出两个环境变量(第一个环境变量允许生成解码映射，~~,~~ 用于从记录的跟踪中解码符号

**Comment by weiminye** [comment]
added 第3章.md
