### ISSUE TITLE
【语法】3.3.2 Perfcollect 添加在脚本本身中可以看到的详细列表和可用设置

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#58]
原文： `默认情况下，所有事件都是从DotNetRuntime:* and DotNetRuntimePrivate:*组中添加在脚本本身中可以看到的详细列表和可用设置)`

问题：语句读不通，括号不匹配，也理解不到意思

参考：【阵亡】

**Comment by weiminye** [comment]
改为：
默认情况下，所有事件都来自DotNetRuntime:*和DotNetRuntimePrivate:*组（我们可以在脚本本身中看到详细列表和可用设置）
