### ISSUE TITLE
【语法】 3.3.3Trace Compass 其方式比庞大的文本转储更为用户友好和信息丰富

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#59]
原文：其方式比庞大的文本转储更为用户友好和信息丰富

问题：比较词没有读通， 方式 比 xx 更为用户友好和信息丰富 这个比较看起来语法不对

参考：其方式比庞大的文本转储来说，对用户更友好而且信息更丰富

**Comment by weiminye** [comment]
经过讨论，最终决定不做修改
