### ISSUE TITLE
1.1.2寄存器机 遵循我们的伪汇编语言缺少主语

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#6]
> 能否想象一台机器的指令集允许我们直接在内存上执行操作，而不需要将数据加载到寄存器中呢？遵循我们的伪汇编语言，它可能看起来更简洁、更高级，因为从内存到寄存器及其相反过程没有额外的加载/存储指令：

`遵循我们的伪汇编语言` 这句话缺少主语，谁遵循

**Comment by weiminye** [comment]
查看了英文原文，也没有明确指出，我认为应该是”编程如果遵循我们的伪汇编语言“，但是没有充分的支持理由，所以留下空间给读者自己理解吧。updated at https://www.cnblogs.com/adalovelacer/p/pro-dot-net-memory-management-guide-1.html
