### ISSUE TITLE
【知识】 3.3.3Trace Compass 我们感兴趣的LTTng数据位于lttngTrace子文件夹中

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#60]
原文： 我们感兴趣的LTTng数据位于lttngTrace子文件夹中，更具体地说，位于lttngTrace\auto-20170801-103533\ust\uid\1000\64-bit之后的路径中

问题： 我猜用户找不到这个文件夹，因为这是一个例子。这里的 auto-20170801-103533 是 auto-年月日 的方式命名的，因此这是一个例子而已，而不是实际读者可以从这里找到

参考：更具体地说，位于如 lttngTrace\auto-20170801-103533\ust\uid\1000\64-bit 之后的路径中

**Comment by weiminye** [comment]
以添加脚注的方式来处理，added into 第3章.md
