### ISSUE TITLE
【错别字】 5.1分区策略 根据你的经验里程可能会有所不同

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#66]
原文：根据你的经验里程可能会有所不同

问题：根据你的经验里程应该是历程

参考：根据你的经验历程可能会有所不同

**Comment by weiminye** [comment]
英文原文是mileage，只有“里程”的意思没有”历程“的意思，所以此处翻译正确无误。
