### ISSUE TITLE
【知识】 5.2按大小分区 它将对象引用的浅大小计算为引用

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#68]
![图片](https://user-images.githubusercontent.com/16054566/92724986-060b2f00-f39e-11ea-9390-ea31c666a4c4.png)

原文：它将对象引用的浅大小计算为引用

问题：应该是浅表大小而不是浅大小

参考：它将对象引用的浅表大小计算为引用

**Comment by lindexi** [comment]
https://docs.microsoft.com/zh-cn/dotnet/api/system.object.memberwiseclone?view=netcore-3.1

**Comment by weiminye** [comment]
added into 第5章.md
