### ISSUE TITLE
【知识】 5.2按大小分区 在附加计划阶段，将决定执行其中一个

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#69]
原文： 在Microsoft的小对象堆的情况下，已经实现了清除和就地压缩回收。 在附加计划阶段，将决定执行其中一个。

问题： 原文的 将决定执行其中一个 说的不够细致，建议再次重复说清除和就地压缩回收执行其中一个

参考： 在Microsoft的小对象堆的情况下，已经实现了清除和就地压缩回收。 在附加计划阶段，将决定执行清除和就地压缩回收其中一个

**Comment by weiminye** [comment]
added into 第5章.md
