### ISSUE TITLE
1.1.2寄存器机 是有像IBM System/360这样的机器 缺少说明

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#7]
> 是的，是有像IBM System/360这样的机器，但是如今我不知道还有任何此类产品用于生产。

那么 IBM System/360这样的机器有什么特点

另外 "用于生产" 是否作为 `用于生产环境` 会好一点

**Comment by lindexi** [comment]
是的，尽管世界上是有像IBM System/360 这样允许我们直接在内存上执行操作，而不需要将数据加载到寄存器中的机器，但是至今没有知道还有什么此类产品被用于生产环境中

**Comment by weiminye** [comment]
好建议！add into 第1章.md
