### ISSUE TITLE
【语法】 5.2按大小分区 单个阈值为8000字节

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#71]
原文： 当前对于Mono 5.4，单个阈值为8,000字节

问题： 单个阈值为字节，阈值为字节？ 应该是对象

参考： 单个对象的阈值为8,000字节

**Comment by lindexi** [comment]
单个对象大小的阈值为8,000字节

**Comment by lindexi** [comment]
或者再多加点重复如何

当前对于 Mono 5.4 版本，决定对象应该放在小对象堆或大对象堆的依据是对象的大小。以单个对象大小的阈值为8,000字节为界限，所有较大的对象都在Mono大对象存储区(LOS - Large object Store)的区域里分配，较小的对象则在托儿所（Nursery）里分配

**Comment by weiminye** [comment]
可以采用“单个对象大小的阈值为8,000字节”。 至于后面的那段“当前对于 Mono 5.4 版本，决定对象应该放在小对象堆或大对象堆的依据是对象的大小。以单个对象大小的阈值为8,000字节为界限，所有较大的对象都在Mono大对象存储区(LOS - Large object Store)的区域里分配，较小的对象则在托儿所（Nursery）里分配”只能放在阅读指南里
