### ISSUE TITLE
【语法】 5.2按大小分区 这些测试选择了一系列不同的各种方案

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#72]
原文： 这些测试选择了一系列不同的各种方案，包括内部和外部团队

问题： 测试选择了内部和外部团队？ 有点怪，是否 包括内部和外部团队的各种方案

参考：这些测试选择了一系列包括内部和外部团队不同的各种方案

**Comment by weiminye** [comment]
added into 第5章.md
