### ISSUE TITLE
【语法】 5.2.2大对象堆 并且不大于给定的大小阈值的大对象堆分配则没有其他例外

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#75]
原文：我们在代码中分配的对象、并且不大于给定的大小阈值的大对象堆分配则没有其他例外

问题：我们在代码中分配的对象则没有其他例外？代码中分配的没有其他例外？ 表示没读懂

参考：阵亡

**Comment by weiminye** [comment]
应为：我们在代码中分配的、并且不大于给定的大小阈值的大对象堆分配并没有其他例外情况。

 added into 第5章.md
