### ISSUE TITLE
【知识】 它们还将包含在解析NGENed程序集的字符串文本期间创建的字符串

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#77]
原文： 它们还将包含在解析NGENed程序集的字符串文本期间创建的字符串string(并且由于 NoStringIntern 选项而未使用string暂留的)

问题： 我认为 NGENed 程序集的意思应该是使用 NGen 生成程序集之后，解析这个程序集。也就是说这个程序集是被 NGen 生成的

参考：

**Comment by weiminye** [comment]
同意。added into 第5章.md
它们还将包含在解析NGen生成的程序集的字符串文本期间创建的字符串
