### ISSUE TITLE
【知识】 5.2.2大对象堆 是不太可能出现LargeHeapHandleTable的问题的

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#78]
原文： 在我们的应用程序中，是不太可能出现LargeHeapHandleTable的问题的。一般来说，可能会是在需要(动态地)创建大量静态成员或加载许多动态 AppDomains时

问题： 一个知识点问题，好像没有说 Linq 的问题。第二个是建议重复

参考：在我们的应用程序中，是不太可能出现LargeHeapHandleTable的问题的。一般来说，可能**出现问题**会是在需要(动态地)创建大量静态成员或加载许多动态 AppDomains时

补充知识点：在出现大量的 Linq 创建泛形时可能会出现问题。 这个知识点需要再找权威的，我只有一篇相关的博客 https://blog.lindexi.com/post/dotnet-%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BC%80%E6%BA%90%E7%9A%84%E8%BF%90%E8%A1%8C%E6%97%B6%E4%BB%93%E5%BA%93%E4%BB%A3%E7%A0%81%E5%87%8F%E5%B0%91%E4%BD%BF%E7%94%A8-Linq-%E8%AF%AD%E5%8F%A5.html

**Comment by weiminye** [comment]
added into 第5章.md

补充知识点放在阅读指南https://www.cnblogs.com/adalovelacer/p/pro-dot-net-memory-management-guide-5.html 里面，因为现在出版社不容许在书里加链接了。
