### ISSUE TITLE
【语法】 6.1 内存分配简介 Book Of The Runtime对此总结道

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#79]
原文：Book Of The Runtime对此总结道：“每次分配一个大对象时会考虑整个Large Object Heap。分配小对象仅考虑暂留

问题：这里的 Book Of The Runtime 需要加上书名号

参考：《Book Of The Runtime》这本书对此总结道

**Comment by weiminye** [comment]
已添加进“第6章.md”
