### ISSUE TITLE
1.1.3 堆栈 缺少 子例程 的进一步描述

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#8]
堆栈从一开始就与计算机编程有着内在的联系，这主要是因为子例程的概念

那么什么是 子例程 呢？是否需要括号说明

**Comment by weiminye** [comment]
added into https://www.cnblogs.com/adalovelacer/p/pro-dot-net-memory-management-guide-1.html
