### ISSUE TITLE
【知识】 6.2Bump Pointer分配 有人会好奇在对象A所在的内存中发生了什么

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#80]
原文：有人会好奇在对象A所在的内存中发生了什么

问题：应该是在分配之前发生了什么，没有时态

参考：

- 是否有人会好奇在给对象A分配所使用的内存时发生了什么？

- 有人会好奇在给对象A分配所使用的内存时发生了什么。

- 有人会好奇在给对象A分配内存时发生了什么。

**Comment by weiminye** [comment]
结合英文原文，经过讨论，该处不做处理，不过还是谢谢
