### ISSUE TITLE
【知识】 6.2Bump Pointer分配 为了使新对象处于干净状态，它所在的内存必须被清零

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#81]
原文： 为了使新对象处于干净状态，它所在的内存必须被清零

问题： 这不是必须的，在 .NET 5 中可以通过特性标记让对象申请内存时不清空

参考：

**Comment by lindexi** [comment]
https://github.com/dotnet/runtime/pull/454

**Comment by weiminye** [comment]
出版社不让在书里加链接。所以这样处理：
建议加脚注：***这不是必须的，在 .NET 5 中可以通过SkipLocalsInitAttribute特性标记让对象申请内存时不清空***
