### ISSUE TITLE
【语法】 第7章 垃圾回收 所以我们知道如何创建对象

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#83]
原文：我们已经了解了分配器(Allocator)，所以我们知道如何创建对象。现在是时候该学习如何以及何时删除对象

问题：和后一句没有强联系

参考：我们已经了解了分配器(Allocator)，所以我们**已经**知道如何创建对象。现在是时候该学习如何以及何时删除对象

**Comment by weiminye** [comment]
已加入‘第7章.md’
