### ISSUE TITLE
【语法】 第7章 垃圾回收 这四章都有内在的联系，要想获得全面的知识，应该全部都要阅读

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#84]
原文：这四章都有内在的联系，要想获得全面的知识，应该全部都要阅读

问题：主语不对， 这四章...要想获得全面的知识 

参考：这四章都有内在的联系，如果你要想获得全面的知识，那么这四章应该全部都要阅读

**Comment by weiminye** [comment]
已加入到'第7章.md'
