### ISSUE TITLE
【知识】 7.2GC流程的示例 这就是为什么要注意不要像我们稍后讨论的那样引入太多不必要的全面回收

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#85]
原文： 这就是为什么要注意不要像我们稍后讨论的那样引入太多不必要的全面回收

问题： 这里的 “全面回收” 和上文的 “这种情况通常被称为“完全垃圾回收”(以下大部分时间会将其称为“全 GC”)” 定义的 完全垃圾回收 不相同。建议使用相同的词

参考：这就是为什么要注意不要像我们稍后讨论的那样引入太多不必要的完全垃圾回收

**Comment by weiminye** [comment]
采纳之，addinto '第7章.md'
