### ISSUE TITLE
【语法】 7.3GC流程的步骤 你可以把它们当作一张地图，把我们带到它们的尽头

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#86]
原文： 你可以把它们当作一张地图，把我们带到它们的尽头

问题： 把我们带到它们的尽头？其实我理解不了。我尝试修改为终点等词，好像也理解不了。理解不了的内容是 为什么要把我们带到它们的尽头？它们是？尽头是？

参考：

**Comment by weiminye** [comment]
这里是指所描述的步骤就像一幅地图。最终决定改为：你可以把这些描述当作一张地图，以引领你前进。
