### ISSUE TITLE
【语法】 7.4分析GC 重新定位(更新地址)花费的时间比压缩本身(移动对象)更多可能更令人惊讶

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#88]
原文：重新定位(更新地址)花费的时间比压缩本身(移动对象)更多可能更令人惊讶

问题：缺少逗号，看起来是两句

参考：重新定位(更新地址)花费的时间比压缩本身(移动对象)更多，这可能更令人惊讶

**Comment by weiminye** [comment]
采纳之，addinto '第7章.md'
