### ISSUE TITLE
1.1.3 堆栈 因此让我们看看它们是如何开始的 这句话没读通过

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#9]
> 今天的.NET大量使用“调用堆栈”和“堆栈”概念，因此让我们看看它们是如何开始的

这个 因此 没有强因果关系，在英文中只是表示转折

另外在中文中 “是如何开始的” 好像也不是很好的描述

**Comment by lindexi** [comment]
今天的.NET大量使用“调用堆栈”和“堆栈”概念，请让我们看看它们是如何工作的

**Comment by lindexi** [comment]
今天在.NET里大量使用“调用堆栈”和“堆栈”概念，请让我们看看它们是如何工作的

**Comment by weiminye** [comment]
updated into 第1章.md
