### ISSUE TITLE
【语法】 7.5垃圾回收性能调优数据 LOH预算超出了，该GC提升为全面GC

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#90]
原文： LOH预算超出了，该GC提升为全面GC

问题： 和上文的 “这种情况通常被称为“完全垃圾回收”(以下大部分时间会将其称为“全 GC”)” 定义的 完全垃圾回收 不相同。建议使用相同的词

参考：LOH预算超出了，该GC提升为完全垃圾回收

**Comment by weiminye** [comment]
addinto '第7章.md'
