### ISSUE TITLE
【知识】 7.6回收触发器 可以通过使BitmapSource实现IDisposable接口并分别在其构造函数和Dispose方法中调用GC.AddMemoryPressure和GC.RemoveMemoryPressure来完成

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#95]
原文：可以通过使BitmapSource实现IDisposable接口并分别在其构造函数和Dispose方法中调用GC.AddMemoryPressure和GC.RemoveMemoryPressure来完成

问题：有两个问题，一个是是否需要注释这两个方法的作用。另一个是这个做法的描述和官方说的不相同

在官方文档说 AddMemoryPressure 的作用是 通知运行时在安排垃圾回收时应考虑分配大量的非托管内存 请看 [GC.AddMemoryPressure(Int64) 方法 (System) | Microsoft Docs](https://docs.microsoft.com/zh-cn/dotnet/api/system.gc.addmemorypressure?view=netcore-3.1 )

在上面这个文档也说到 AddMemoryPressure和 RemoveMemoryPressure 方法只为仅依赖于终结器释放非托管资源的类型的类型提高了性能。 不需要在遵循 dispose 模式的类型中使用这些方法，也就是 Dispose方法中调用GC.AddMemoryPressure和GC.RemoveMemoryPressure来完成 这个做法和官方建议是不同的

**Comment by weiminye** [comment]
采纳之，addinto '第7章.md'
