### ISSUE TITLE
【知识】 8.5GC句柄根 除非我们在代码中执行了大量长耗时异步I/O操作

### ISSUE THREAD

**Issue by lindexi** [weiminye/pro-dotnet-memory-mgr-translation-review#96]
原文：但是，由于此种句柄仅用于CLR的内部需求，所以在我们的日常工作中并不需要关注它们，除非我们在代码中执行了大量长耗时异步I/O操作(由于磁盘碎片化所致)导致固定操作的开销成为

问题：非IO 也可以，如锁，请看 https://blog.lindexi.com/post/dotnet-%E4%BD%BF%E7%94%A8-SemaphoreSlim-%E5%8F%AF%E8%83%BD%E7%9A%84%E5%86%85%E5%AD%98%E6%B3%84%E9%9C%B2.html

参考：，除非我们在代码中执行了大量长耗时异步I/O操作或大量进入没有被释放的内核锁

**Comment by weiminye** [comment]
added into '第8章.md'
